# Generated by Django 3.1.7 on 2021-03-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210306_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='oraganisation',
            new_name='organisation',
        ),
    ]
